apiVersion: v1
kind: Pod
metadata:
  name: wid-demo-with-sa
  namespace: wid-kns
spec:
  containers:
  - image: google/cloud-sdk:slim
  # we are using this sdk because gcloud cli will be installed.
    name: wid-demo-with-sa
    command: ["sleep","infinity"]
  serviceAccountName: wid-ksa
  # this is the workload identity mapped K8s SA
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
    # pod needs to be on a node where the GKE MDS is enabled